%YAML1.2
---
acceptMultipart: true
autoOrdering: true
locale: en
secret: 'keyboard cat' #TODO generate automatically
secure: false #TODO
session:
  resave: false
  saveUninitialized: false
shuffleFactor: 1
...