%YAML1.2
---
acceptMultipart: true
auth: false
autoOrdering: true
locale: en
mongo:
  url: mongodb://localhost:27017
  options: false
secret: 'keyboard cat' #TODO generate automatically
secure: false #TODO
session:
  resave: false
  saveUninitialized: false
shuffleFactor: 1
...